### ISSUE TITLE
so- whenever i try to launch totem counter and join ANY surivial world or multiplayer world this issue pops up "The game crashed whilst unexpected error Error: java.lang.NullPointerException: Cannot invoke "net.uku3lig.totemcounter.config.TotemCounterConfig$TotemDisplayConfig.isEnabled()" because "this.config" is null" i use fabric 1.19.2

### ISSUE THREAD

**Issue by examinatory** [uku3lig/totemcounter#3]

**Comment by uku3lig** [comment]
try deleting `.minecraft/config/totemcounter.toml`

**Comment by examinatory** [comment]
i cant find that code

**Comment by examinatory** [comment]
> try deleting `.minecraft/config/totemcounter.toml`

uh so i tried doing that and now whenever i launch totem counter this pops up- <html>RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by<br>'advanced_runtime_resource_pack'!</html>
<html>at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)<br>at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)<br>at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)<br>at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)<br>at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)<br>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)<br>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)</html>
<html>EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by<br>'advanced_runtime_resource_pack'</html>
<html>at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)<br>at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)<br>... 4 more</html>
RuntimeException: Mixin transformation of net.devtech.arrp.ARRP failed
<html>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)<br>at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)<br>at java.base/java.lang.Class.forName0(Native Method)<br>at java.base/java.lang.Class.forName(Class.java:467)<br>at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)<br>at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)<br>at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)<br>... 5 more</html>
<html>MixinApplyError: Mixin [nametagping.mixins.json:EntityRendererMixin from mod nametagping] from phase [DEFAULT] in config<br>[nametagping.mixins.json] FAILED during PREPARE</html>
<html>at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)<br>at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)<br>at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)<br>at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)<br>at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)<br>at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)<br>at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)<br>at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)<br>... 14 more</html>
ClassNotFoundException: The specified mixin 'nametagping.nametagping.mixin.EntityRendererMixin' was not found
<html>at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1314)<br>at org.spongepowered.asm.mixin.transformer.MixinInfo.&lt;init&gt;(MixinInfo.java:858)<br>at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852)<br>at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:781)<br>at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)<br>... 20 more</html>

**Comment by examinatory** [comment]
> try deleting `.minecraft/config/totemcounter.toml`

I can't find the code for that, Am I missing something?

**Comment by uku3lig** [comment]
in your .minecraft folder, there is a config folder, in which you will find a file named `totemcounter.toml`; delete that file

**Comment by examinatory** [comment]
> in your .minecraft folder, there is a config folder, in which you will find a file named `totemcounter.toml`; delete that file

Thank you so much that fixed it. You are a life saver
