### ISSUE TITLE
Game crashed while rendering entity

### ISSUE THREAD

**Issue by S-olp** [uku3lig/totemcounter#5]
java.lang.NullPointerException: Cannot invoke "net.uku3lig.totemcounter.config.TotemCounterConfig$ExperimentalConfig.isDisableArmorStands()" because the return value of "net.uku3lig.totemcounter.config.TotemCounterConfig.getExperimentalConfig()" is null

![image_2023-11-10_160828131](https://github.com/uku3lig/totemcounter/assets/150484029/68cb9fc0-6d9c-435d-ae88-25f0a44876be)

**Comment by uku3lig** [comment]
delete `.minecraft/config/totemcounter.toml`
