### ISSUE TITLE
Using sinytra connector not working 

### ISSUE THREAD

**Issue by Beez3-A** [uku3lig/totemcounter#8]
Cant seem to get your mod to work on forge using sinytra connector

Cool mod though

**Comment by uku3lig** [comment]
works fine on my machine

which minecraft version are you on

**Comment by Beez3-A** [comment]
Im on 1.20.1 

Maybe it could be a conflicting mod then
I have like 170 + mods
including totem cooldown and totem charm slot

I don't know if that is conflicting ?
other features of your mod work such as the color xp bar, but the actual totem count does not show.

**Comment by uku3lig** [comment]
once again works perfectly fine for me on 1.20.1

make sure you downloaded the correct mod versions, as far as i know the two mods you mentioned should not cause breakage

**Comment by Beez3-A** [comment]
I have the correct mod versions, that's for sure. 

anyways ill update you if I get it to work. 

Thanks
